### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by ewildgoose** [comment]
Hi! Wow, thanks, that's quite a comprehensive update to the documentation! Appreciated!

Can I ask what motivated you to do these updates? Not complaining just always curious?

After a quick look the only thing which caught my eye is that I think you drop the .elixirls exception from the .gitignore? I'm using vscode with the elixirls plugin and it's useful to exclude it's assets. Do you think you could just tweak that part of your proposed patch please?

**Comment by kianmeng** [comment]
> Hi! Wow, thanks, that's quite a comprehensive update to the documentation! Appreciated!

Welcome.

> Can I ask what motivated you to do these updates? Not complaining just always curious?

Fixing typos or documentation while code reading the particular Elixir library.

> After a quick look the only thing which caught my eye is that I think you drop the .elixirls exception from the .gitignore? I'm using vscode with the elixirls plugin and it's useful to exclude it's assets. Do you think you could just tweak that part of your proposed patch please?

Isn't ElixirLS already self-ignored the `.elixir_ls` folder? I tried this after opening the source code using VSCode.

```bash
$ cat .elixir_ls/.gitignore 
*
```

**Comment by kianmeng** [comment]
@ewildgoose Any updates on this?

**Comment by ewildgoose** [comment]
This is brilliant. Thanks, committed. I appreciate your work on this - apologies for the slow response, I think I need to check github settings, for some reason I don't seem to get notifications, but only on this repo?

**Comment by kianmeng** [comment]
No worries, just follow up on long pending PRs. Probably need to re-check your GitHub's setting. Thanks.

:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
