### PR TITLE
🏷️ Set Fault type to integer

### LINKED ISSUE #21: Wrong type for XMLRPC.Fault faut_code causes dialyzer warning
The following code

```elixir
    case XMLRPC.decode!(body) do
      %XMLRPC.Fault{fault_code: 2} -> IO.inspect("fault 2")
    end
```

makes dialyzer complain:

```console
The pattern can never match the type.

Pattern:
%XMLRPC.Fault{:fault_code => 2}

Type:
%{
  :__struct__ => XMLRPC.Fault | XMLRPC.MethodCall | XMLRPC.MethodResponse,
  :fault_code => Integer,
  :fault_string => binary(),
  :method_name => binary(),
  :param =>
    false
    | nil
    | true
    | binary()
    | [false | nil | true | binary() | number()]
    | number()
    | map(),
  :params => [
    false
    | nil
    | true
    | binary()
    | [false | nil | true | binary() | number()]
    | number()
    | map()
  ]
}
```

The type is defined as:

```elixir
    @type t :: %__MODULE__{fault_code: Integer, fault_string: String.t}
```

I suppose it should be `integer` instead of `Integer`

### PR DESCRIPTION
**Pull request by graham2071**
Closes #21 

Also set the latest version in README (1.4).

### CODE REVIEW

**Comment by graham2071** [comment]
@ewildgoose Would you able to merge this and create a release ? I am ok to help, but I don't know how.

**Comment by ewildgoose** [comment]
Hi, merged
Apologies for not going it sooner. There might be something wrong with how I have the alerts setup in github, I get notifications for other repositories, but only "some" for this repo!?

I can create a new release when I return from travelling, however, it might be more than 1 week.

**Comment by graham2071** [comment]
That would be perfect, thanks !

**Comment by graham2071** [comment]
Hi @ewildgoose , thank you for the merge !
Is there a way I may help you for releasing the package to hex ? I can't see a new version [here](https://hex.pm/packages/xmlrpc).

**Comment by ewildgoose** [comment]
Done!
Sorry for the slow update, have been travelling.

**Comment by graham2071** [comment]
Thanks !

**Pull request merged**
